# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Barbicha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Barbicha
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'CodableFirebase', :git => 'https://github.com/alickbass/CodableFirebase.git'
  pod 'SipHash', '~> 1.2'


  target 'BarbichaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
